{
    "name": "C18 DMS",
    "summary": "Metadata-driven document management for Odoo 18 Community",
    "version": "18.0.1.0.0",
    "category": "Documents",
    "author": "Custom18",
    "license": "LGPL-3",
    "depends": ["mail", "project", "hr", "board"],
    "data": [
        "security/c18_dms_security.xml",
        "security/ir.model.access.csv",
        "data/c18_dms_mail_template_data.xml",
        "data/c18_dms_demo.xml",
        "data/c18_dms_cron.xml",
        "views/c18_dms_menu.xml",
        "views/dms_directory_views.xml",
        "views/dms_type_views.xml",
        "views/dms_tag_views.xml",
        "views/dms_document_views.xml",
        "views/dms_dashboard_views.xml",
        "views/dms_history_views.xml",
        "views/dms_share_templates.xml",
        "wizards/dms_multi_upload_wizard_views.xml",
        "wizards/dms_share_audit_export_wizard_views.xml",
        "wizards/dms_share_token_wizard_views.xml",
    ],
    "application": True,
    "installable": True,
}
